name: hello-actions

on:
  push:
    branches: [main]

jobs:
  hello-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-step
        run: |
          cat /etc/*-release && echo "\n"
          echo "Node: " && node --version
          echo "Ruby: " && ruby --version
          echo "\n"
          echo "::warning::Esta é uma mensagem de aviso"
          echo "::error::Esta é uma mensagem de erro"
