# name é opcional
# - se não existe vai ser o nome do arquivo;
# - se repetido vai aparecer duas vzs no menu (nome do arquivo diferencía);
name: Hello Actions

on:
  push:
    branches: ['hello/*']

jobs:
  hello-action-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Ubuntu
        # já vem com diversas linguagens instaladas (muda com OS)
        run: |
          cat /etc/*-release && echo "\n"
          echo "Node: " && node --version
          echo "Ruby: " && ruby --version
  hello-action-windows:
    runs-on: windows-latest
    steps:
      - name: Hello Windows
        run: |
          Write-Host "Versão do Windows:"
          Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, OsArchitecture
          echo "Node: "; node --version
          echo "Ruby: "; ruby --version
  hello-action-macos:
    runs-on: macos-latest
    steps:
      - name: Hello MacOS
        run: |
          sw_vers
          echo "Node: " && node --version
          echo "Ruby: " && ruby --version
