name: Hello Actions

on:
  push:
    branches: ['hello/*']

jobs:
  hello-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-step
        # jรก vem com diversas linguagens instaladas
        run: |
          cat /etc/*-release && echo "\n"
          echo "Node: " && node --version
          echo "Ruby: " && ruby --version
