name: Cache

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Dependencies
        id: node-modules  
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-3
      - name: Cow say
        run: npx cowsay "Hello from step 1!""
  use:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Use Cached Dependencies
        id: node-modules  
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-3
      - name: Cow say
        run: npx cowsay Moo!
