name: Cache

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get my stuff
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: node-modules  
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependenceies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm ci
  use:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Get my stuff
        uses: actions/checkout@v4
      - name: Use Cached Dependencies
        id: node-modules  
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependenceies
      #   if: steps.node-modules.cache-hit != 'true'
      #   run: npm ci
      - name: Cow say
        run: npx cowsay Moo!
