name: Conditions

on: workflow_dispatch

jobs:
  conditions:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: if 0  # <- step condition
        if: 0
        run: echo "0!"
      - name: if 1
        if: 1
        run: echo "1!"
      - name: if true
        if: true
        run: echo "true!"
  on-failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Deu ruim
        run echo "Deu ruim!"