name: Conditions

on: workflow_dispatch

jobs:
  conditions:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: if 0  # <- step condition
        if: 0
        run: echo "0!"
      - name: if 1
        if: 1
        run: echo "1!"
      - name: if true
        if: true
        run: echo "true!"
  on-failure:
    needs: conditions  # sem isso nunca seria executado
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Deu ruim
        run: echo "Deu ruim!"
  on-success:
    needs: conditions  # sem isso nunca seria executado
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Foi tudo bem
        run: echo "Deu bão!"
    on-cancelled:
    needs: conditions  # sem isso nunca seria executado
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Foi cancelado
        run: echo "Foi cancelado!"
    always:
    needs: conditions  # sem isso nunca seria executado
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Sempre
        run: echo "Sempre!"