name: Deploy Node Project

on:
  push:
    branches: [main, workflow_dispatch]

jobs:
  tests:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest # já vem com Node, Python, Ruby, Julia
    steps:
      # não roda no repo, tenho que baixar a branch:
      - name: Get my stuff
        # https://github.com/actions/checkout
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4
      # - name: Install Node
      #   uses: actions/setup-node
      #   with:
      #     node-vesion: 24
      - name: Cache Dependencies
        uses: actions/cache@v4
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm ci  # use only .lock
      - name: Run tests
        run: npm t
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get my stuff
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
          with:
            path: ~/.npm
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build application
        run: |
          npm ci
          npm run build
      - name: Upload Artifacts
        # vai criar um link de download (vou usar o artifacts do hub como área de transfência)
        ## /actions/actions/runs/15680483301/artifacts/3335669167
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: list
        run: ls -la
      - name: Deploy
        run: echo "'I'm deployed baby!"

