name: Error

on: workflow_dispatch

jobs:
  error:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: exit 0
      - name: Everything is fine
        run: exit 1
      - name: I never run
        run: echo "I realy never run"
