name: Error

on: workflow_dispatch

jobs:
  error:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        id: erroed-step  # para ser referenciado no if
        run: exit 0
      - name: Everything is fine
        run: exit 1
      - name: I never run
        run: echo "I realy never run"
  canceled:
    needs: error  # depende de error, será cancelado
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "I will never run"
  runs:
    # não tem relação com erro, vai ser executado normalmente
    runs-on: ubuntu-latest
    steps:
      - name: Everything is fine
        continue-on-error: true # esse step pode falhar
        run: exit 1
      - name: Continue on error
        run: echo "Continue on error"
  runs-if-failed:
    # vai rodar se error falhar
    runs-on: ubuntu-latest
    # .outputs .outcome .conclusion
    # .outcome: 'success' | 'failure' | 'cancelled' | 'skiped'
    steps:
      - name: Run if failed
        if: failure() && steps.erroed-step.outcome == 'failure'
        run: echo "Hello there!"
