name: Matrix

on: workflow_dispatch

jobs:
  matrix:
    continue-on-error: true
    strategy:
      matrix:
        names: [primus, secundos, tercius]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: hello-step
        run: echo "${{ matrix.name }}"
