name: Matrix

on: workflow_dispatch

jobs:
  matrix:
    strategy:
      matrix:
        names: [primus, secundos, tercius]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: hello-step
        run: echo "${{ matrix.names }}"
  in-ex-clude:
    continue-on-error: true
    strategy:
      matrix:
        names: [primus, secundos]
        os: [ubuntu-latest, macos-latest]
        # posso incluir combinações:
        include:
          - names: tercius
            os: ubuntu-latest
        # posso excluir combinações da matriz:
        exclude:
          - names: secundos
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: hello-step
        run: echo "${{ matrix.names }}"
