name: Outputs

on:
  push:
    branches: [main]

jobs:
  hello-action-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-step
        run: |
          echo "::notice file={"name"},title={"title"}::Hello there!"
          echo "::debug::Está é uma mesnsagem de debug"
          echo "::warning::Esta é uma mensagem de aviso"
          echo "::error::Esta é uma mensagem de erro"


