name: Reusable Workflow with Inputs

on:
  workflow_call:
    inputs:
      name:
        description: A name to be printed
        required: true
        type: string
      number:
        description: A number to be printed
        required: false
        default: 42
        type: number
    secrets: # bem parecido com inputs
      my-secret:
        required: true

jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo ${{ inputs.name }}
      - name: Print number
        run: echo ${{ inputs.number }}
      - name: Print secret
        run: echo ${{ secrets.my-secret }}
