name: Using Reusable Workflow with Outputs

on: workflow_dispatch

jobs:
  primus:
    runs-on: ubuntu-latest
    steps:
      - name: Using Reusable Workflow
        run: echo "The workflow must contain at least one job with no dependencies"
  secundos:
    needs: primus
    uses: ./.github/workflows/reusable-with-outputs.yaml
  tertius:
    needs: primus
    runs-on: ubuntu-latest
    steps:
      - name: Use output value
        run: ${{ needs.primus.outputs.name }} # need: steps do qual depende
