name: Using Reusable Workflow with Outputs

on: workflow_dispatch

jobs:
  primus:
    needs: primus
    uses: ./.github/workflows/reusable-with-outputs.yaml
  secundos:
    needs: primus
    runs-on: ubuntu-latest
    steps:
      - name: Use output value
        run: ${{ needs.primus.outputs.name }} # need: steps do qual depende
