name: Deploy Node Project

on:
  push:
    branches: [main, workflow_dispatch]

jobs:
  tests:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-latest # já vem com Node, Python, Ruby, Julia
    steps:
      # não roda no repo, tenho que baixar a branch:
      - name: Get my stuff
        # https://github.com/actions/checkout
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4
      # - name: Install Node
      #   uses: actions/setup-node
      #   with:
      #     node-vesion: 24
      - name: Install
        run: npm ci  # use only .lock
      - name: Run tests
        run: npm t
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get my stuff
        uses: actions/checkout@v4
      - name: Build application
        run: |
          npm ci
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "'I'm deployed baby!"

